backups/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^export_xml/$', views.export_xml, name='exportXML'),
    url(r'^import_xml/$', views.import_xml, name='importXML')
]

carrets/urls.py
from django.conf.urls import url
from carrets import views

urlpatterns = [
    url(r'^actualitzar_carret/(?P<idNau>[0-9]+)/$', views.actualitzar_carret, name='actualitzarCarret'),
    url(r'^veure_comanda/$', views.veure_comanda, name='veureComanda'),
    url(r'^veure_comanda/confirmar_carret/$', views.confirmar_carret, name='confirmarCarret'),
    url(r'^veure_comanda/esborrar_linia/(?P<idNau>[0-9]+)/$', views.esborrar_linia, name='esborrarLinia'),
    url(r'^veure_comanda/esborrar_comanda/$', views.esborrar_comanda, name='esborrarComanda'),
    url(r'^llista_comandes/$', views.llista_comandes, name='llistaComandes'),
    url(r'^llista_comandes/detall/(?P<comanda_id>[0-9]+)/$', views.detall_comanda, name='detallComanda')
]

ciutadaestelar/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from usuaris import views as logins

urlpatterns = (
    [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('naus.urls', namespace="ciutadaestelar")),
    url(r'^carret/', include('carrets.urls', namespace="carrets")),
    url(r'^perfil/$', logins.vista_perfil, name="perfil"),
    url(r'^perfil/restaurar/$', logins.vista_reset, name="restaurarContrasenya"),
    url(r'^backups/', include('backups.urls', namespace="backups")),
    url(r'^login/$', logins.vista_login, name="login"),
    url(r'^logout/$', logins.vista_logout, name="logout"),
    url(r'^registre/$', logins.vista_registre, name="registre"),
    url(r'^hangar/$', logins.vista_hangar, name="hangar"),
    url(r'^taller/$', logins.modifica_nau, name="taller"),
    url(r'^venta/$', logins.ven_nau, name="venta")
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

naus/urls.py
from django.conf.urls import url, include
from naus import views

urlpatterns = [
    #seccio pagina
    url(r'^$', views.inici, name="inici"),
    url(r'^wiki/$', views.wiki, name='wiki'),
    url(r'^botiga/$', views.botiga, name='botiga'),
    #seccio naus
    url(r'^naus/$', views.naus, name='naus'),
    url(r'^nau/', views.infonau, name='infoNau'),
    url(r'^nau/(?P<idNau>.+)/$', views.nau, name="nau"),
    url(r'^afegir_nau/$', views.editanau, name='afegirnau'),
    url(r'^editar_nau/(?P<idNau>.+)/$', views.editanau, name='editarnau'),
    url(r'^eliminar_nau/(?P<idNau>.+)/$', views.eliminanau, name='eliminarnau'),
    #seccio armes
    url(r'^armes/$', views.armes, name='armes'),
    url(r'^arma/(?P<idArma>.+)/$', views.arma, name="arma"),
    url(r'^afegir_arma/$', views.editaarma, name='afegirarma'),
    url(r'^editar_arma/(?P<idArma>.+)/$', views.editaarma, name='editararma'),
    url(r'^eliminar_arma/(?P<idArma>.+)/$', views.eliminaarma, name='eliminararma'),
    #seccio misils
    url(r'^misils/$', views.misils, name='misils'),
    url(r'^misil/(?P<idMisil>.+)/$', views.misil, name='misil'),
    url(r'^afegir_misil/$', views.editamisil, name='afegirmisil'),
    url(r'^editar_misil/(?P<idMisil>.+)/$', views.editamisil, name='editarmisil'),
    url(r'^eliminar_misil/(?P<idMisil>.+)/$', views.eliminamisil, name='eliminarmisil'),
    #seccio fabricants
    url(r'^fabricants/$', views.fabricants, name='fabricants'),
    url(r'^afegir_fabricant/$', views.editafabricant, name='afegirfabricant'),
    url(r'^editar_fabricant/(?P<idFabricant>.+)/$', views.editafabricant, name='editarfabricant'),
    url(r'^eliminar_fabricant/(?P<idFabricant>.+)/$', views.eliminafabricant, name='eliminarfabricant')
    
    
]

templates/partials/layout_missatge.html
<div class="col-xs-12 col-sm-12 col-md-12">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="alert {% if message.tags %} alert-{{message.tags}} {% endif %}">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{message}}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

templates/partials/layout_modal.html
<!--posar aqui el modal i adaptar de tasca anterior-->
<div id="modal-item" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">[[Nau.nom]]</h4>
            </div>
            <div class="modal-body text-justify">
                <p>[[Nau.descripcio]]</p>
            </div>
            <div ng-if="Nau.video" class="modal-footer">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe ng-src="[[Nau.video]]" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

templates/partials/navbar_usuari.html
{% if user.is_anonymous %}
<li class="nav-item">
    <a href="{% url 'login' %}">Login</a>
</li>
{% else %} {% if user.is_staff %}
<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle capitalize" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.username}} <span class="caret"></span></a>
    <div class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item" href="{% url 'ciutadaestelar:naus' %}"><span class="oi oi-list-alt dropdown-li-space"></span> Mostrar Naus</a>
        <a class="dropdown-item" href="{% url 'ciutadaestelar:armes' %}"><span class="oi oi-list-alt dropdown-li-space"></span> Mostrar Armes</a>
        <a class="dropdown-item" href="{% url 'ciutadaestelar:misils' %}"><span class="oi oi-list-alt dropdown-li-space"></span> Mostrar Misils</a>
        <a class="dropdown-item" href="{% url 'ciutadaestelar:fabricants' %}"><span class="oi oi-list-alt dropdown-li-space"></span> Mostrar Fabricants</a>
        <a class="dropdown-item" href="{% url 'ciutadaestelar:afegirnau' %}"><span class="oi oi-plus dropdown-li-space"></span> Afegir Nau</a>
        <a class="dropdown-item" href="{% url 'ciutadaestelar:afegirarma' %}"><span class="oi oi-plus dropdown-li-space"></span> Afegir Arma</a>
        <a class="dropdown-item" href="{% url 'ciutadaestelar:afegirmisil' %}"><span class="oi oi-plus dropdown-li-space"></span> Afegir Misil</a>
        <a class="dropdown-item" href="{% url 'ciutadaestelar:afegirfabricant' %}"><span class="oi oi-plus dropdown-li-space"></span> Afegir Fabricant</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'backups:exportXML' %}"><span class="oi oi-export dropdown-li-space"></span> Exportar dades a XML</a>
        <a class="dropdown-item" href="{% url 'backups:importXML' %}"><span class="oi oi-import dropdown-li-space"></span> Importar dades a XML</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'logout' %}"><span class="oi oi-log-out dropdown-li-space"></span> Sortir</a>
    </div>
</li>
{% else %}
<a class="wall-entry icon-space-left" href="{% url 'carrets:veureComanda' %}"><span class="oi oi-cart"></span></a>
<li class="nav-item dropdown dropdown-menu-left">
    <a href="#" class="nav-link dropdown-toggle capitalize" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.username}} <span class="caret"></span></a>
    <div class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item" href="{% url 'perfil' %}"><span class="oi oi-wrench dropdown-li-space"></span>Perfil</a>
        <a class="dropdown-item" href="{% url 'carrets:llistaComandes' %}"><span class="oi oi-tag dropdown-li-space"></span> Les meves compres</a>
        <a class="dropdown-item" href="{% url 'hangar' %}"><span class="oi oi-wrench dropdown-li-space"></span>Hangar</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'logout' %}"><span class="oi oi-log-out dropdown-li-space"></span> Sortir</a>
    </div>
</li>
{% endif %} {% endif %}