carrets/urls.py
from django.conf.urls import url
from carrets import views

urlpatterns = [
    url(r'^actualitzar_carret/(?P<idNau>[0-9]+)/$', views.actualitzar_carret, name='actualitzarCarret'),
    url(r'^veure_comanda/$', views.veure_comanda, name='veureComanda'),
    url(r'^veure_comanda/confirmar_carret/$', views.confirmar_carret, name='confirmarCarret'),
    url(r'^veure_comanda/esborrar_linia/(?P<idNau>[0-9]+)/$', views.esborrar_linia, name='esborrarLinia'),
    url(r'^veure_comanda/esborrar_comanda/$', views.esborrar_comanda, name='esborrarComanda'),
    url(r'^llista_comandes/$', views.llista_comandes, name='llistaComandes'),
    url(r'^llista_comandes/detall/(?P<comanda_id>[0-9]+)/$', views.detall_comanda, name='detallComanda')
]

ciutadaestelar/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from usuaris import views as logins

urlpatterns = (
    [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('naus.urls', namespace="ciutadaestelar")),
    url(r'^carret/', include('carrets.urls', namespace="carrets")),
    url(r'^perfil/$', logins.vista_perfil, name="perfil"),
    url(r'^perfil/restaurar/$', logins.vista_reset, name="restaurarContrasenya"),
    url(r'^backups/', include('backups.urls', namespace="backups")),
    url(r'^login/$', logins.vista_login, name="login"),
    url(r'^logout/$', logins.vista_logout, name="logout"),
    url(r'^registre/$', logins.vista_registre, name="registre"),
    url(r'^hangar/$', logins.vista_hangar, name="hangar"),
    url(r'^taller/$', logins.modifica_nau, name="taller"),
    url(r'^venta/$', logins.ven_nau, name="venta")
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

naus/urls.py
from django.conf.urls import url, include
from naus import views

urlpatterns = [
    #seccio pagina
    url(r'^$', views.inici, name="inici"),
    url(r'^wiki/$', views.wiki, name='wiki'),
    url(r'^botiga/$', views.botiga, name='botiga'),
    #seccio naus
    url(r'^naus/$', views.naus, name='naus'),
    url(r'^nau/', views.infonau, name='infoNau'),
    url(r'^nau/(?P<idNau>.+)/$', views.nau, name="nau"),
    url(r'^afegir_nau/$', views.editanau, name='afegirnau'),
    url(r'^editar_nau/(?P<idNau>.+)/$', views.editanau, name='editarnau'),
    url(r'^eliminar_nau/(?P<idNau>.+)/$', views.eliminanau, name='eliminarnau'),
    #seccio armes
    url(r'^armes/$', views.armes, name='armes'),
    url(r'^arma/(?P<idArma>.+)/$', views.arma, name="arma"),
    url(r'^afegir_arma/$', views.editaarma, name='afegirarma'),
    url(r'^editar_arma/(?P<idArma>.+)/$', views.editaarma, name='editararma'),
    url(r'^eliminar_arma/(?P<idArma>.+)/$', views.eliminaarma, name='eliminararma'),
    #seccio misils
    url(r'^misils/$', views.misils, name='misils'),
    url(r'^misil/(?P<idMisil>.+)/$', views.misil, name='misil'),
    url(r'^afegir_misil/$', views.editamisil, name='afegirmisil'),
    url(r'^editar_misil/(?P<idMisil>.+)/$', views.editamisil, name='editarmisil'),
    url(r'^eliminar_misil/(?P<idMisil>.+)/$', views.eliminamisil, name='eliminarmisil'),
    #seccio fabricants
    url(r'^fabricants/$', views.fabricants, name='fabricants'),
    url(r'^afegir_fabricant/$', views.editafabricant, name='afegirfabricant'),
    url(r'^editar_fabricant/(?P<idFabricant>.+)/$', views.editafabricant, name='editarfabricant'),
    url(r'^eliminar_fabricant/(?P<idFabricant>.+)/$', views.eliminafabricant, name='eliminarfabricant')
    
    
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ca">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{pagetitle|default:"Ciutada Estelar"}}</title>
    <link href="{% static 'icon/favicon.ico' %}" rel="shortcut icon" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/open-iconic-bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet" /> {% block estils %}{% endblock %}

</head>

<body ng-app="appCiutadaEstelar">
    {% block body %}

        <nav id="navbar" class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="/">Ciutada Estelar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'ciutadaestelar:wiki' %}">Wiki </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ciutadaestelar:botiga' %}">Botiga</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Joc</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if not user.is_staff %}
                    <li class="nav-item">
                        <a href="{% url 'carrets:veureComanda' %}">
                    <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> 
                </li>
        {% endif %}
        {% include 'partials/navbar_usuari.html' %}
             </ul>
        </div>
    </nav>
        {% include 'partials/layout_missatge.html' %}
    <div id="contingut" class="container-fluid">
        {% block contingut %} {% endblock %}
    </div>
    {% endblock %}
    <footer>
    <div class="container">
      <div class="row">

        <div class="col-sm-4">
          <div class="foot-header">
            ENLLAÇOS
          </div>
          <div class="foot-links">
            <a href="#">INICI</a></br>
                        <a href="#sobre">SOBRE MI</a></br>
                        <a href="#serveis">SERVEIS</a></br>
            </div>
            </div>
            <div class="col-sm-4">
                <div class="foot-header">
                    INFORMACIO DE CONTACTE
                </div>
                <div class="foot-links">
                    <p>
                        C/ Arquitecte Pelai Mendoza, 21 </br>
                        17400 Figueres, Girona </br> CATALUNYA </br>
                    </p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="foot-header">
                    SEGUEIX-NOS
                </div>
                <div class="foot-links">
                    <a class="btn btn-social-icon btn-twitter">
              <span class="fa fa-twitter"></span>
            </a>
                    <a class="btn btn-social-icon btn-google">
              <span class="fa fa-google"></span>
            </a>
                    <a class="btn btn-social-icon btn-facebook">
              <span class="fa fa-facebook"></span>
            </a>
                </div>
            </div>
            </div>
            <!--/container-->
            </footer>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
            {% block scripts %}{% endblock %}
</body>

</html>

templates/perfil.html
{%extends 'base.html' %} {% load staticfiles %}{%block estils%}
<link href="{% static 'css/info-menu.css' %}" rel="stylesheet"> {%endblock%}{% block contingut %}
<div class="container">Editar el perfil</div>
<div class="panel-body">
    <div class="jumbotron text-justify" style="padding:2em 1em 1em 2em;">
        <p>Hola, benvingut/da a la nostre botiga. <span class="capitalize">{{user.username}}</span>, si vols veure les teves comandes fes <a href="{% url 'carrets:llistaComandes' %}">clic aquí</a>.</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-8">
        <table class="table table-hover table-bordered table-striped">
            <tbody>
                <tr>
                    <td colspan="2"><small>Dades de l'usuari</small></td>
                </tr>
                <tr>
                    <th class="th-hidden">Usuari</th>
                    <td class="capitalize">{{user.username}}</td>
                </tr>
                <tr>
                    <th class="th-hidden">Correu electrònic</th>
                    <td>{{user.email}}</td>
                </tr>
                <tr>
                    <th class="th-hidden">Modificar contrasenya</th>
                    <td>
                        <a class="wall-entry" href="{% url 'restaurarContrasenya' %}">
                            Canviar la contrasenya
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}