carrets/urls.py
from django.conf.urls import url
from carrets import views

urlpatterns = [
    url(r'^actualitzar_carret/(?P<idNau>[0-9]+)/$', views.actualitzar_carret, name='actualitzarCarret'),
    url(r'^veure_comanda/$', views.veure_comanda, name='veureComanda'),
    url(r'^veure_comanda/confirmar_carret/$', views.confirmar_carret, name='confirmarCarret'),
    url(r'^veure_comanda/esborrar_linia/(?P<idNau>[0-9]+)/$', views.esborrar_linia, name='esborrarLinia'),
    url(r'^veure_comanda/esborrar_comanda/$', views.esborrar_comanda, name='esborrarComanda'),
    url(r'^llista_comandes/$', views.llista_comandes, name='llistaComandes'),
    url(r'^llista_comandes/detall/(?P<comanda_id>[0-9]+)/$', views.detall_comanda, name='detallComanda')
]

ciutadaestelar/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from usuaris import views as logins

urlpatterns = (
    [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('naus.urls', namespace="ciutadaestelar")),
    url(r'^carret/', include('carrets.urls', namespace="carrets")),
    url(r'^perfil/$', logins.vista_perfil, name="perfil"),
    url(r'^perfil/restaurar/$', logins.vista_reset, name="restaurarContrasenya"),
    url(r'^backups/', include('backups.urls', namespace="backups")),
    url(r'^login/$', logins.vista_login, name="login"),
    url(r'^logout/$', logins.vista_logout, name="logout"),
    url(r'^registre/$', logins.vista_registre, name="registre"),
    url(r'^hangar/$', logins.vista_hangar, name="hangar"),
    url(r'^taller/$', logins.modifica_nau, name="taller"),
    url(r'^venta/$', logins.ven_nau, name="venta")
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

naus/urls.py
from django.conf.urls import url, include
from naus import views

urlpatterns = [
    #seccio pagina
    url(r'^$', views.inici, name="inici"),
    url(r'^wiki/$', views.wiki, name='wiki'),
    url(r'^botiga/$', views.botiga, name='botiga'),
    #seccio naus
    url(r'^naus/$', views.naus, name='naus'),
    url(r'^nau/', views.infonau, name='infoNau'),
    url(r'^nau/(?P<idNau>.+)/$', views.nau, name="nau"),
    url(r'^afegir_nau/$', views.editanau, name='afegirnau'),
    url(r'^editar_nau/(?P<idNau>.+)/$', views.editanau, name='editarnau'),
    url(r'^eliminar_nau/(?P<idNau>.+)/$', views.eliminanau, name='eliminarnau'),
    #seccio armes
    url(r'^armes/$', views.armes, name='armes'),
    url(r'^arma/(?P<idArma>.+)/$', views.arma, name="arma"),
    url(r'^afegir_arma/$', views.editaarma, name='afegirarma'),
    url(r'^editar_arma/(?P<idArma>.+)/$', views.editaarma, name='editararma'),
    url(r'^eliminar_arma/(?P<idArma>.+)/$', views.eliminaarma, name='eliminararma'),
    #seccio misils
    url(r'^misils/$', views.misils, name='misils'),
    url(r'^misil/(?P<idMisil>.+)/$', views.misil, name='misil'),
    url(r'^afegir_misil/$', views.editamisil, name='afegirmisil'),
    url(r'^editar_misil/(?P<idMisil>.+)/$', views.editamisil, name='editarmisil'),
    url(r'^eliminar_misil/(?P<idMisil>.+)/$', views.eliminamisil, name='eliminarmisil'),
    #seccio fabricants
    url(r'^fabricants/$', views.fabricants, name='fabricants'),
    url(r'^afegir_fabricant/$', views.editafabricant, name='afegirfabricant'),
    url(r'^editar_fabricant/(?P<idFabricant>.+)/$', views.editafabricant, name='editarfabricant'),
    url(r'^eliminar_fabricant/(?P<idFabricant>.+)/$', views.eliminafabricant, name='eliminarfabricant')
    
    
]

carrets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

class Comanda(models.Model):
    comanda_id = models.AutoField(primary_key=True)
    usuari = models.ForeignKey(User)
    data = models.DateField(auto_now=True)
    carrer = models.CharField(verbose_name="Carrer", max_length=50, help_text="El nom del carrer on enviarem la comanda.")
    poblacio = models.CharField(verbose_name="Població", max_length=30, help_text="La població a la qual pertany el carrer.")
    codi_postal = models.PositiveIntegerField(verbose_name="Codi Postal", help_text="El codi postal de la població.")
    provincia = models.CharField(verbose_name="Província", max_length=30, help_text="La província a la qual pertany la població.")
    pagaments = (('CRE', 'Credits'),
              ('DIN', 'Diners')
              )
    pagament = models.CharField(max_length=3, choices=pagaments, default='D')

class Linia(models.Model):
    linia_id = models.AutoField(primary_key=True)
    comanda_id = models.ForeignKey('Comanda')
    producte_id = models.ForeignKey('naus.Nau')
    preu = models.DecimalField(max_digits=5, decimal_places=2)
    quantitat = models.PositiveIntegerField()
    pagaments = (('CRE', 'Credits'),
              ('DIN', 'Diners')
              )
    pagament = models.CharField(max_length=3, choices=pagaments, default='D')

carrets/forms.py
from django import forms

class edit_carret(forms.Form):
    quantitat = forms.IntegerField(min_value=1, widget=forms.NumberInput(attrs={'autofocus':'autofocus'}))

carrets/views.py
from __future__ import unicode_literals
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.forms import modelform_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import user_passes_test
from naus.models import Nau
from carrets.models import Comanda, Linia
from usuaris.models import Hangar
from .forms import edit_carret

def actualitzar_carret(request,idNau):
    nau = get_object_or_404(Nau,pk=idNau)
    if request.method=='POST':
        form = edit_carret(request.POST)
        if form.is_valid():
            if 'carret' not in request.session:
                request.session['carret']={}
            quantitat=form.cleaned_data['quantitat']
            request.session['carret'].update({idNau:quantitat})
            messages.add_message(request,messages.SUCCESS,'El producte s\'ha afegit dins el carret')
            return HttpResponseRedirect(reverse('ciutadaestelar:botiga'))
        else:
            messages.error(request,'Hi ha errors en el formulari')
    else:
        form=edit_carret()

    form.helper=FormHelper()
    return render(request,'carrets/editarcarret.html',{'form':form,'nau':nau})

def veure_comanda(request):
    if 'carret' not in request.session:
        request.session['carret']={}
    cistella=[]
    totDiners=0
    totCredits=0
    for id in request.session['carret']:
        nau=Nau.objects.get(id=id)
        quantitat=request.session['carret'][id]
        preu=nau.preu*quantitat
        totDiners+=preu
        preuCredits=nau.preucredits*quantitat
        totCredits+=preuCredits
        cistella.append({'nau':nau,
                        'quantitat':quantitat,
                        'preu':preu,
                        'preucredits':preuCredits
                        })
    return render(request,'carrets/carret.html',{'cistella':cistella,'totalDiners':totDiners, 'totalCredits':totCredits})

def esborrar_linia(request,idNau):
    request.session.modified=True
    producte=request.session['carret']
    if idNau in producte:
        del producte[idNau]
    return HttpResponseRedirect(reverse('carrets:veureComanda'))
    
def esborrar_comanda(request):
    if 'carret' in request.session:
        request.session['carret']={}
    return HttpResponseRedirect(reverse('carrets:veureComanda'))

@user_passes_test(lambda u:u.is_authenticated(), login_url='/login/')
def confirmar_carret(request):
    formConfirmarCarret = modelform_factory(Comanda,exclude=('comanda_id','usuari','data'))
    comanda=Comanda()
    if request.method == 'POST':
        form=formConfirmarCarret(request.POST,request.FILES,instance=comanda)
        if form.is_valid():
            carrer=form.cleaned_data['carrer']
            poblacio=form.cleaned_data['poblacio']
            codi_postal=form.cleaned_data['codi_postal']
            provincia=form.cleaned_data['provincia']
            pagament=form.cleaned_data['pagament']
            total_credits=0
            if 'carret' in request.session:
                if request.session['carret']:
                    comanda.carrer=carrer
                    comanda.poblacio=poblacio
                    comanda.codi_postal=codi_postal
                    comanda.provincia=provincia
                    comanda.usuari=request.user
                    comanda.pagament=pagament
                    comanda.save()
                    carret=request.session['carret']
                    
                    for id in carret:
                        producte=Nau.objects.get(id=id)
                        quantitat=carret[id]
                        linia=Linia()
                        linia.comanda_id=comanda
                        linia.producte_id=producte
                        linia.quantitat=quantitat
                        linia.preu=producte.preu
                        linia.pagament=pagament
                        linia.save()
                        total_credits+=producte.preu*quantitat
                        request.session['carret']={}
                    if pagament is 'CRE':
                        usuari=request.user
                        hangar=Hangar.objects.get(usuari=usuari)
                        if total_credits < hangar.credits :
                            messages.error(request,'No tens suficients credits')
                            return HttpResponseRedirect(reverse('carrets:veureComanda'))
                    return HttpResponseRedirect(reverse('carrets:llistaComandes'))
                else:
                    messages.error(request,'No hi ha cap producte al carret')
            else:
                return HttpResponseRedirect(reverse('ciutadaestelar:botiga'))
        else:
            messages.error(request,'Hi ha errors en el formulari')
    else:
        form= formConfirmarCarret(instance=comanda)
        
    form.helper=FormHelper()
    form.helper.form_class='blueForms'
    form.helper.label_class='col-lg-2'
    form.helper.field_class='col-lg-10'
    form.helper.add_input(Submit('submit','Finalitzar compra'))
    return render(request,'carrets/confirmar-carret.html',{'form':form})
    
@user_passes_test(lambda u:u.is_authenticated(), login_url='/login/')
def llista_comandes(request):
    comandes=Comanda.objects.filter(usuari=request.user)
    return render(request, 'carrets/llista_comandes.html',{'comandes':comandes})
    
@user_passes_test(lambda u:u.is_authenticated(), login_url='/login/')
def detall_comanda(request,comanda_id):
    preu_comanda=0
    pagament = None
    comanda=[]
    linias =Linia.objects.filter(comanda_id=comanda_id)
    for linia in linias.all():
        nau=Nau.objects.get(id=linia.producte_id.id)
        quantitat=linia.quantitat
        preu=linia.preu*quantitat
        preu_comanda+=preu
        pagament=linia.pagament
        comanda.append({'nau':nau,
                        'quantitat':quantitat,
                        'preu':preu
                        })
    return render(request,'carrets/detall.html',{'comanda':comanda,'preu_comanda':preu_comanda,'pagament':pagament})

carrets/templates/carrets/carret.html
{% extends 'base.html' %} {% load staticfiles %} {%block estils%}
<link href="{% static 'css/info-menu.css' %}" rel="stylesheet"> {%endblock%}
{% block contingut%}
<div class="panel-heading">Llista de productes</div>
<div class="panel-body">
    {% if cistella %}
    <div class="table-responsive">
        <table id="no-more-tables" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Imatge</th>
                    <th>Unitats</th>
                    <th>Preu</th>
                    <th>Editar</th>
                </tr>
            </thead>
            <tbody>
                {% for carret in cistella %}
                <tr>
                    <td data-title="Nom">{{carret.nau.nom}}</td>
                    <td data-title="Imatge">
                        <img src="{{carret.nau.imatge.url}}" style="width:100px;">
                    </td>
                    <td data-title="Unitats">{{carret.quantitat}}</td>
                    <td data-title="Preu">{{carret.preu}} €</td>
                    <td data-title="Editar">
                        <div class="btn-group">
                            <a class="wall-entry" href="{% url 'carrets:actualitzarCarret' carret.nau.pk %}"><span class="oi oi-pencil"></span></a>
                            <a class="wall-entry" href="{% url 'carrets:esborrarLinia' carret.nau.pk %}"><span class="oi oi-trash"></span></a>
                             </div>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <th class="text-right th-hidden" colspan="4">Preu total</th>
                    <td data-title="Total">{{preu_comanda}} €</td>
                </tr>
            </tbody>
        </table>
        <div class="btn-group">
            <a class="btn btn-info" role="button" href="{% url 'carrets:esborrarComanda' %}"><span class="oi oi-remove"></span> Cancel·lar comanda</a>
            <a class="btn btn-primary" role="button" href="{% url 'carrets:confirmarCarret' %}"><span class="oi oi-ok"></span> Confirmar comanda</a>
        </div>
    </div>
    {% else %}
    <p>No hi han productes en el carret.</p>
    {% endif %} {% endblock %}

carrets/templates/carrets/confirmar-carret.html
{% extends 'base.html' %} {% load staticfiles %} {% load crispy_forms_tags %} {% block contingut %}
<div class="panel-heading">Finalitzar Comanda</div>
<div class="panel-body">
    {% crispy form %}
</div>
{% endblock %}

carrets/templates/carrets/detall.html
{% extends 'base.html' %} {% load staticfiles %} {%block estils%}
<link href="{% static 'css/info-menu.css' %}" rel="stylesheet"> {%endblock%} {% block contingut%}
<div class="panel-body">
    {% if comanda %}
    <div class="table-responsive">
        <table id="no-more-tables" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th class="th-hidden">Imatge</th>
                    <th>Unitats</th>
                    <th>Preu</th>
                </tr>
            </thead>
            <tbody>
                {% for linia in comanda %}
                <tr>
                    <td data-title="Nom">{{linia.nau.nom}}</td>
                    <td class="td-hidden"><img src="{{linia.nau.imatge.url}}" alt="{{linia.nau.nom}}" style="width:100px;"></td>
                    <td data-title="Unitats">{{linia.quantitat}}</td>
                    <td data-title="Preu">{{linia.preu}} €</td>
                </tr>
                {% endfor %}
                <tr>
                    <th class="text-right th-hidden" colspan="3">Preu total</th>
                    <td data-title="Total">{{preu_comanda}} €</td>
                </tr>
            </tbody>
        </table>
    </div>
    {% else %}
    <p>No hi ha cap comanda amb aquest número de ID.</p>
    {% endif %}
</div>
{% endblock %} {% block scripts %}</script>
{% endblock %}

carrets/templates/carrets/editarcarret.html
{% extends 'base.html' %} {% load staticfiles %} {% load crispy_forms_tags %} {%block estils%}
<link href="{% static 'css/botiga.css' %}" rel="stylesheet">
<link href="{% static 'css/info-menu.css' %}" rel="stylesheet">{%endblock%} {% block contingut%}
<div class="panel-heading">Afegint al carret</div>
<div class="panel-body">
    <div class="panel-body" ng-app="myApp">
        {% if nau %}
        <form id="form" method="post">
            <div class="table-responsive">
                <table id="no-more-tables" class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Imatge</th>
                            <th>Unitats</th>
                            <th>Preu</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td data-title="Nom">{{nau.nom}}</td>
                            <td data-title="Imatge">
                                <img src="{{nau.imatge.url}}" style="width:100px;">
                            </td>
                            <td data-title="Unitats" ng-model="quantity">{% crispy form %}</td>
                            <td data-title="Preu" ng-model="price">{{nau.preu}}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="btn-group">
                    <a class="btn btn-info" role="button" href="{{request.META.HTTP_REFERER}}"><span class="glyphicon glyphicon-remove"></span> Enrere</a>
                    <button class="btn btn-primary" role="button" type="submit" form="form" value="Submit"><span class="glyphicon glyphicon-ok"></span> Confirmar producte</button>
                </div>
            </div>
        </form>
        {% else %}
        <p>La ID del producte no és vàlida.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

carrets/templates/carrets/llista_comandes.html
{% extends 'base.html' %} {% load staticfiles %} {%block estils%}
<link href="{% static 'css/info-menu.css' %}" rel="stylesheet"> {%endblock%} {% block contingut%}
<div class="panel-heading">Llista de comandes</div>
<div class="panel-body">
    {% if comandes %}
    <div class="table-responsive">
        {% for comanda in comandes reversed %}
        <table id="no-more-tables" class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Nº comanda</th>
                    <th>Data</th>
                    <th>Pagament</th>
                    <th>Pagament</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td data-title="Nº Com.">{{comanda.comanda_id}}</td>
                    <td data-title="Data">{{comanda.data}}</td>
                    <td data-title="Estat">{{comanda.pagament}}</td>
                    <td data-title="Detall">
                        <div class="btn-group">
                            <a class="btn btn-primary" role="button" href="{% url 'carrets:detallComanda' comanda.comanda_id %}">
                                <span class="oi oi-zoom-in"></span>
                            </a>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        {% endfor %}
    </div>
    {% else %}
    <p>No hi ha cap comanda realitzada.</p>
    {% endif %}
{% endblock %} {% block scripts %}
{% endblock %}